#!/bin/bash
# header_jme433.inc

# Ask user for student name

read -p "Enter your name: " name

# Ask user for student id

read -p "Enter your student ID: " student_id

# Display the banner

echo "======================================="
echo "             Assignment 2              "
echo "          by $name ($student_id)       "
echo "         Part1: Log analyzer           "
echo "======================================="
echo  
